import '../geo/domain/geo_region.dart';

const continents = [
  GeoRegion.europe,
  GeoRegion.southAmerica,
  GeoRegion.africa,
  GeoRegion.asia,
  GeoRegion.oceania,
  GeoRegion.world,
];
const destinations = [
  GeoRegion.europe,
  GeoRegion.usa,
  GeoRegion.southAmerica,
  GeoRegion.india,
  GeoRegion.australia,
  GeoRegion.japan,
  GeoRegion.africa,
  GeoRegion.canada,
  GeoRegion.asia,
  GeoRegion.brazil,
  GeoRegion.germany,
  GeoRegion.uk,
  GeoRegion.oceania,
  GeoRegion.mexico,
  GeoRegion.china,
  GeoRegion.indonesia,
  GeoRegion.argentina,
  GeoRegion.world,
];
const regionNotes = {
  GeoRegion.europe: 'A mosaic of little wonders',
  GeoRegion.usa: 'From sea to shining sea',
  GeoRegion.southAmerica: 'Follow the Andes south',
  GeoRegion.india: 'A world within a country',
  GeoRegion.australia: 'Discover the great down under',
  GeoRegion.japan: 'An island story',
  GeoRegion.africa: 'A continent of contrasts',
  GeoRegion.canada: 'The great northern adventure',
  GeoRegion.asia: 'Across an extraordinary continent',
  GeoRegion.brazil: 'Into the heart of South America',
  GeoRegion.germany: 'Sixteen pieces, one journey',
  GeoRegion.uk: 'A little island adventure',
  GeoRegion.oceania: 'An ocean of discoveries',
  GeoRegion.mexico: 'Color around every corner',
  GeoRegion.china: 'An atlas of ancient landscapes',
  GeoRegion.indonesia: 'An archipelago to explore',
  GeoRegion.argentina: 'From the tropics to Patagonia',
  GeoRegion.world: 'The whole world is yours',
};
