"""Validate reviewed targets and export the offline Dart corpus. No network needed."""
import argparse, collections, hashlib, json, re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
parser.add_argument('--release', action='store_true')
args = parser.parse_args()
review = ROOT / 'data/corpus_review/review.json'
rows = json.loads(review.read_text())
allowed = {'9', '5+4', '4+5', '6+3', '3+6', '7+2', '2+7'}
accepted = sorted((r for r in rows if r['approved']), key=lambda r: r['text'])
seen = set()
for r in accepted:
    t = r['text']; key = t.replace(' ', '')
    assert re.fullmatch('[A-Z]+(?: [A-Z]+)?', t), t
    assert len(key) == len(set(key)) == 9, t
    pattern = '+'.join(str(len(w)) for w in t.split())
    assert pattern in allowed and pattern == r['pattern'], t
    assert key not in seen, f'Duplicate {t}'
    assert r.get('reviewer') and r.get('source') and r.get('reason'), t
    seen.add(key)
assert {r['pattern'] for r in accepted} == allowed
if args.release and len(accepted) < 2000:
    sys.exit(f'RELEASE BLOCKED: {len(accepted)} approved targets; at least 2000 required.')
for license in ['ESDB', 'WordNet']:
    assert (ROOT / f'assets/licenses/{license}.txt').is_file()
content = "// Generated by tool/build_corpus.py from the editorial review ledger.\n"
content += "import '../game/phrase.dart';\n\n"
content += "const corpusVersion = '2026-10-02';\nconst List<Phrase> corpus = [\n"
for r in accepted:
    tier = 'pair' if ' ' in r['text'] else 'single'
    content += f"  Phrase(text: '{r['text']}', tier: PhraseTier.{tier}),\n"
content += "];\n\nList<Phrase> corpusForTier(PhraseTier tier) =>\n    corpus.where((p) => p.tier == tier).toList();\n"
target = ROOT / 'lib/data/corpus.dart'
if args.check:
    assert target.read_text() == content, 'Generated corpus differs from approved ledger. Run tool/build_corpus.py.'
else:
    target.write_text(content)
report = {'version': '2026-10-02', 'approved': len(accepted), 'not_shipped': len(rows)-len(accepted),
          'patterns': dict(sorted(collections.Counter(r['pattern'] for r in accepted).items())),
          'sources': dict(collections.Counter(r['source'] for r in accepted)),
          'review_method': 'AI editorial review by Codex; not independent human review',
          'ledger_sha256': hashlib.sha256(review.read_bytes()).hexdigest()}
if args.check:
    assert json.loads((ROOT / 'data/corpus_review/report.json').read_text()) == report, 'Review report is stale'
if not args.check:
    (ROOT / 'data/corpus_review/report.json').write_text(json.dumps(report, indent=2)+'\n')
print(json.dumps(report, indent=2))
