import 'dart:convert';
import 'dart:ui';

import 'package:flutter/foundation.dart' show compute;
import 'package:flutter/services.dart' show rootBundle;

import '../domain/geo_piece.dart';
import '../domain/geo_fit.dart';
import '../domain/geo_region.dart';

/// A loaded region pack — the runtime side of `assets/geo/<id>.json`,
/// generated by `tools/build-geo-packs.mjs`.
///
/// Packs are immutable and cached per region after the first load, since
/// the geometry never changes within a session.
class GeoPack {
  GeoPack({
    required this.region,
    required this.name,
    required this.version,
    required this.viewBox,
    required this.pieces,
  });

  final GeoRegion region;

  /// Region display name, as baked into the pack.
  final String name;

  /// Pack schema/content version — bumped when the build tool reshapes a
  /// region; lets a future remote-refresh path detect staleness.
  final int version;

  /// Normalized coordinate space all piece geometry lives in. Origin is
  /// the top-left `(0, 0)`; this is its width and height.
  final Size viewBox;

  final List<GeoPiece> pieces;

  // Enclaves must paint and receive taps above their surrounding regions.
  late final List<GeoPiece> paintOrder = List.of(pieces)
    ..sort(
      (a, b) => (b.bounds.width * b.bounds.height).compareTo(
        a.bounds.width * a.bounds.height,
      ),
    );
  late final Map<String, Path> _paths = {
    for (final p in pieces)
      p.id: GeoFit(
        scale: 1,
        origin: Offset.zero,
        viewBox: viewBox,
      ).screenPath(p),
  };

  GeoPiece? pieceAt(Offset point) {
    for (final piece in paintOrder.reversed) {
      if (_paths[piece.id]!.contains(point)) return piece;
    }
    return null;
  }

  Path? _silhouette;

  /// The whole region as a single fillable [Path] in viewBox
  /// coordinates. Every piece's polygon is appended as a sub-path; we
  /// deliberately do NOT run `Path.combine(union)` because that is
  /// roughly O(n²) — for a 50–150-piece pack it dominates the setup
  /// screen's first frames and produces a visible 1–3s freeze. At
  /// thumbnail scale the seams between touching neighbors are
  /// invisible under a solid fill, so the simple append yields the
  /// same look at a fraction of the cost. Computed once and cached.
  Path get silhouette => _silhouette ??= _buildSilhouette();

  Path _buildSilhouette() {
    final merged = Path();
    for (final piece in pieces) {
      for (final ring in piece.rings) {
        if (ring.isEmpty) continue;
        merged.moveTo(ring.first.dx, ring.first.dy);
        for (var i = 1; i < ring.length; i++) {
          merged.lineTo(ring[i].dx, ring[i].dy);
        }
        merged.close();
      }
    }
    return merged;
  }

  static final Map<GeoRegion, GeoPack> _cache = <GeoRegion, GeoPack>{};
  static final Map<GeoRegion, Future<GeoPack>> _inflight =
      <GeoRegion, Future<GeoPack>>{};

  /// Loads (and caches) the pack for [region] from the bundled asset.
  /// Concurrent callers share a single in-flight future, so calling
  /// `load` for the same region from multiple widgets won't double-parse.
  static Future<GeoPack> load(GeoRegion region) {
    final cached = _cache[region];
    if (cached != null) return Future.value(cached);
    final inflight = _inflight[region];
    if (inflight != null) return inflight;
    final future = _loadFromAsset(region).whenComplete(() {
      _inflight.remove(region);
    });
    _inflight[region] = future;
    return future;
  }

  static Future<GeoPack> _loadFromAsset(GeoRegion region) async {
    final raw = await rootBundle.loadString(
      'assets/geo/${geoRegionAssetId(region)}.json',
    );
    // The whole decode + GeoPiece construction runs on a background
    // isolate. On a 100+ piece pack the per-piece construction (point
    // copy, bounds compute) is roughly half the cost of the JSON parse —
    // leaving it on the UI isolate still produces visible jank on the
    // setup screen's first frames.
    final decoded = await compute(_decodeGeoPack, raw);
    final pack = GeoPack(
      region: region,
      name: decoded.name ?? geoRegionLabel(region),
      version: decoded.version,
      viewBox: decoded.viewBox,
      pieces: decoded.pieces,
    );
    return _cache[region] = pack;
  }
}

/// Isolate-safe intermediate produced by [_decodeGeoPack]. Holds only
/// plain values + [GeoPiece]s (which themselves use dart:ui's Offset/Rect
/// value types, both of which are safe to send across isolates).
class _DecodedGeoPack {
  _DecodedGeoPack({
    required this.name,
    required this.version,
    required this.viewBox,
    required this.pieces,
  });
  final String? name;
  final int version;
  final Size viewBox;
  final List<GeoPiece> pieces;
}

_DecodedGeoPack _decodeGeoPack(String raw) {
  final json = jsonDecode(raw) as Map<String, dynamic>;
  final viewBox = (json['viewBox'] as List).cast<num>();
  return _DecodedGeoPack(
    name: json['name'] as String?,
    version: json['version'] as int? ?? 1,
    // viewBox is [minX, minY, width, height]; origin is assumed (0, 0).
    viewBox: Size(viewBox[2].toDouble(), viewBox[3].toDouble()),
    pieces: (json['pieces'] as List)
        .map((p) => GeoPiece.fromJson(p as Map<String, dynamic>))
        .toList(growable: false),
  );
}
