import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import '../domain/maze.dart';
import 'regular_vocabulary.dart';
import '../domain/maze_level.dart';

/// Runtime loader for `assets/maze/<level>.json` — the per-difficulty
/// packs generated by `tools/build-maze-packs.mjs`. Packs are immutable
/// and small (~100–230 KB each); we cache per level after the first
/// load so swapping difficulties in the setup screen is free.
class MazePackLoader {
  MazePackLoader._();

  static final Map<MazeLevel, MazePack> _cache = <MazeLevel, MazePack>{};

  static Future<MazePack> load(MazeLevel level) async {
    final cached = _cache[level];
    if (cached != null) return cached;
    final raw = await rootBundle.loadString(
      'assets/maze/${level.assetId}.json',
    );
    final json = jsonDecode(raw) as Map<String, dynamic>;
    final pack = await RegularVocabulary.restore(
      MazePack.fromJson(level, json),
      'en',
    );
    _cache[level] = pack;
    return pack;
  }
}
