import 'package:chaturang/engine/board.dart';
import 'package:chaturang/engine/move_generator.dart';
import 'package:chaturang/engine/opening_book.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_test/flutter_test.dart';

/// The book ships as an asset, generated by a tool that is not run at build
/// time. That makes it the one input to the engine that can silently rot —
/// a stale or mis-encoded book would have the AI open badly with nothing in
/// the logs to say so.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('the bundled book loads, parses, and opens legally', () async {
    final text = await rootBundle.loadString('assets/book/openings.txt');
    final book = OpeningBook.parse(text);
    expect(book.length, greaterThan(0), reason: 'the book is empty');

    // The very first position must be in it, or the book buys nothing.
    final board = Board();
    final first = book.lookup(board.zobrist);
    expect(first, isNotNull, reason: 'no book move for the start position');
    expect(
      MoveGenerator.legalMoves(board),
      contains(first),
      reason:
          'the book opens with an illegal move — it was built against '
          'different move generation, or the encoding has drifted',
    );

    // Walk the book as far as it goes, checking every move it hands back.
    // A single illegal entry anywhere is a build that must not ship.
    var plies = 0;
    while (plies < 40) {
      final move = book.lookup(board.zobrist);
      if (move == null) break;
      expect(
        MoveGenerator.legalMoves(board),
        contains(move),
        reason: 'illegal book move at ply $plies',
      );
      board.makeMove(move);
      plies++;
    }
    expect(
      plies,
      greaterThanOrEqualTo(2),
      reason: 'the book runs out immediately',
    );
  });
}
